import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('owner@example.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('password123');
  await page.getByRole('textbox', { name: 'Password' }).press('Tab');
  await page.getByRole('button', { name: 'Login' }).press('Enter');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'My Homestays' }).click();
  await page.getByRole('button', { name: '+ Add New Homestay' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('Viettel AI');
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).fill('Hanoi');
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('epic tower');
  await page.getByRole('spinbutton', { name: 'Price per Hour (VND)' }).click();
  await page.getByRole('spinbutton', { name: 'Price per Hour (VND)' }).fill('1000000');
  await page.getByRole('spinbutton', { name: 'Max Guests' }).click();
  await page.getByRole('spinbutton', { name: 'Max Guests' }).fill('30');
  await page.getByRole('checkbox', { name: 'WiFi' }).click();
  await page.getByRole('checkbox', { name: 'TV' }).click();
  await page.getByRole('checkbox', { name: 'Kitchen' }).click();
  await page.getByRole('checkbox', { name: 'Parking' }).click();
  await page.getByRole('checkbox', { name: 'Air Conditioning' }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByText('ImagesImage persistence is').click();
  await page.getByRole('button', { name: 'Submit Homestay' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'OU' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@example.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('password123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('HomeAdmin PanelAU').click();
  await page.getByRole('row', { name: 'Viettel AI Owner 2 Hanoi 1.' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Approve' }).click();
  await page.getByRole('row', { name: 'Budget Room Da Lat Owner 2 Da Lat 1.200.000 ₫ Jan 03, 2026 View' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByRole('textbox', { name: 'Reason for Rejection' }).click();
  await page.getByRole('textbox', { name: 'Reason for Rejection' }).fill('ngu');
  await page.getByRole('button', { name: 'Confirm Reject' }).click();
  await page.getByRole('row', { name: 'Da Nang Beach Studio Owner 2 Da Nang 170.000 ₫ Jan 07, 2026 View' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByRole('textbox', { name: 'Reason for Rejection' }).click();
  await page.getByRole('textbox', { name: 'Reason for Rejection' }).fill('ngu2');
  await page.getByRole('button', { name: 'Confirm Reject' }).click();
  await page.getByRole('button', { name: 'AU' }).click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'AU' }).click();
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByRole('button', { name: 'AU' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('user@example.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('password123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'View Details' }).nth(5).click();
  await page.getByRole('button', { name: 'Book Homestay' }).click();
  await page.getByRole('textbox', { name: 'Date' }).fill('82026-02-01');
  await page.getByRole('spinbutton', { name: 'Enter hours' }).click();
  await page.getByRole('spinbutton', { name: 'Enter hours' }).fill('10');
  await page.getByRole('spinbutton', { name: 'Enter number of guests' }).click();
  await page.getByRole('spinbutton', { name: 'Enter number of guests' }).fill('7');
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: '10:00' }).click();
  await page.getByRole('button', { name: 'Confirm Booking' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('slider', { name: 'Maximum' }).click();
  await page.getByText('₫500.000 ₫').click();
  await page.locator('span').nth(4).click();
  await page.getByRole('slider', { name: 'Maximum' }).click();
  await page.getByRole('checkbox', { name: 'WiFi' }).click();
  await page.getByRole('checkbox', { name: 'TV' }).click();
  await page.locator('span').nth(3).click();
  await page.getByRole('slider', { name: 'Minimum' }).click();
  await page.locator('span').nth(3).click();
  await page.getByRole('button', { name: 'CU' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('owner@example.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('password123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('HomeMy HomestaysManage').click();
  await page.getByRole('link', { name: 'My Homestays' }).click();
  await page.getByText('HomeMy HomestaysManage').click();
  await page.getByRole('link', { name: 'Manage Bookings' }).click();
  await page.getByRole('cell', { name: 'pending' }).first().click();
  await page.getByRole('button', { name: 'Accept' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByText('approved', { exact: true }).click();
  await expect(page.locator('tbody')).toContainText('No action');
  await expect(page.locator('tbody')).toContainText('approved');
  await page.getByRole('link', { name: 'Homestay', exact: true }).click();
  await expect(page.getByRole('main')).toMatchAriaSnapshot(`- paragraph: /\\d+\\.\\d+\\.\\d+ ₫ \\/ hour/`);
  await expect(page.getByRole('main')).toContainText('1.000.000 ₫ / hour');
});