import { Request, Response } from 'express';
import { Pool } from 'pg';
import { M_Booking } from '../models/M_Booking';

// 1. Connect to the database using the environment variable we set in Docker
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

// 2. Create the function to handle a new booking request
export const createBooking = async (req: Request, res: Response) => {
  try {
    // Extract the data sent from the React frontend
    const { homestayID, guestID, checkInDate, checkOutDate } = req.body;

    // Create a new booking object using your exact UML Model
    const newBooking = new M_Booking(
      0, // ID is auto-generated by PostgreSQL, so we pass 0 temporarily
      homestayID,
      guestID,
      new Date(checkInDate),
      new Date(checkOutDate)
    );

    const bookingData = newBooking.getBookingDetails();

    // Insert the data into your new PostgreSQL table
    const result = await pool.query(
      `INSERT INTO bookings (homestay_id, guest_id, check_in_date, check_out_date, status) 
       VALUES ($1, $2, $3, $4, $5) RETURNING *`,
      [
        bookingData.homestayID, 
        bookingData.guestID, 
        bookingData.checkInDate, 
        bookingData.checkOutDate, 
        bookingData.status
      ]
    );

    // Send the successful response back to the frontend
    res.status(201).json({
      message: 'Booking successfully created!',
      booking: result.rows[0],
      totalDays: bookingData.totalDays
    });

  } catch (error) {
    console.error('Error creating booking:', error);
    res.status(500).json({ error: 'Failed to create booking' });
  }
};

export const getUserBookings = async (req: Request, res: Response) => {
    try {
      const { userId } = req.params;
      // Fetch bookings for this specific user, newest first
      const result = await pool.query(
        'SELECT * FROM bookings WHERE guest_id = $1 ORDER BY booking_id DESC', 
        [userId]
      );
      res.status(200).json(result.rows);
    } catch (error) {
      console.error('Error fetching bookings:', error);
      res.status(500).json({ error: 'Failed to fetch bookings' });
    }
  };

  export const cancelBooking = async (req: Request, res: Response) => {
    try {
      const { bookingId } = req.params;
      
      // Update the status to 'cancelled' and return the updated row
      const result = await pool.query(
        `UPDATE bookings SET status = 'cancelled' WHERE booking_id = $1 RETURNING *`,
        [bookingId]
      );
  
      if (result.rowCount === 0) {
        return res.status(404).json({ error: 'Booking not found.' });
      }
  
      res.status(200).json({ 
        message: 'Booking cancelled successfully.', 
        booking: result.rows[0] 
      });
    } catch (error) {
      console.error('Error cancelling booking:', error);
      res.status(500).json({ error: 'Failed to cancel booking.' });
    }
  };