import { Request, Response } from 'express';
import { Pool } from 'pg';
import { M_Transaction } from '../models/M_Transaction';

// Connect to the database pool
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

export const createTransaction = async (req: Request, res: Response) => {
    try {
      const { bookingID, amount, paymentMethod } = req.body;
  
      // 1. The Validation Guard (Fixes Test T-02)
      if (!bookingID || !amount || !paymentMethod) {
        return res.status(400).json({ error: 'Missing required payment details.' });
      }
  
      // 2. Package into your MVC Model
      const newTransaction = new M_Transaction(
        0, // ID is auto-generated by the database
        bookingID,
        amount,
        paymentMethod
      );
  
      // 3. Insert the Transaction into PostgreSQL
      const result = await pool.query(
        `INSERT INTO transactions (booking_id, amount, payment_method, status)
         VALUES ($1, $2, $3, 'Success') RETURNING *`,
        [newTransaction.bookingID, newTransaction.amount, newTransaction.paymentMethod]
      );
  
      const savedTransaction = result.rows[0];
  
      // 4. Update the Booking Status to 'Confirmed'
      await pool.query(
        `UPDATE bookings SET status = 'Confirmed' WHERE booking_id = $1`,
        [newTransaction.bookingID]
      );
  
      // 5. Send the successful response and receipt back to React
      res.status(201).json({
        message: 'Payment processed successfully.',
        receipt: savedTransaction
      });
  
    } catch (error) {
      // 6. The Error Catch (Fixes Test T-03)
      console.error('Transaction Error:', error);
      res.status(500).json({ error: 'Failed to process payment.' });
    }
  };